[Layout]

    alt-slash= "Layout tiles horizontal vertical"
    alt-comma= "Layout accordion horizontal vertical"


[Focus]

    alt-h= "Focus left"
    alt-j= "Focus down"
    alt-k= "Focus up"
    alt-l= "Focus right"


[Move]

    "alt-shift-h" = "Move left"
    "alt-shift-j" = "Move down"
    "alt-shift-k" = "Move up"
    "alt-shift-l" = "Move right"


[Resize]

    "alt-shift-minus" = "Resize smart -50"
    "alt-shift-equal" = "Resize smart +50"


[ServiceMode]

    esc= "Reload config"
    r= "Reset layout"
    f= "Toggle between floating and tiling layout"
    backspace= "Close all windows but current"

    "alt-shift-comma" = "Service mode"
    "alt-shift-h" = "Join with left"
    "alt-shift-j" = "Join with down"
    "alt-shift-k" = "Join with up"
    "alt-shift-l" = "Join with right"


[ResizeMode]

    "alt-r" = "Activate resize mode"
    "-" = "Resize smart -50"
    "=" = "Resize smart +50"


[Custom]

    "alt-shift-f" = "Toggle fullscreen"


[Workspaces]

    "alt-<1..9/a..z>" = "Switch to workspace"
    "alt-shift-<1..9/a..z>" = "Move node to workspace"
    "alt-tab" = "Switch back or forth to workspace"
    "alt-shift-tab" = "Move workspace to monitor"


[CustomWorkspaces]

    "1"= "Main"
    "2"= "IDE"
    "3"= "Terminal"
    "4"= "Teams"
    "5"= "Outlook"
    "6"= "Slack"
    "q"= "Spotify"
    "w"= "Writing"
